export interface SomoraWorld {
  id: string;
  name: string;
  iconName: string;
  blurb: string;
  topic: string;
  gradient: string;
  text: string;
  glow: string;
  x: number;
  y: number;
  order: number;
  unlocked: boolean;
}

export const worlds: SomoraWorld[] = [
  {
    id: "curious-grove",
    name: "Curious Grove",
    iconName: "star",
    blurb: "Where every question sprouts a new idea.",
    topic: "Foundations of AI",
    gradient: "from-emerald-400 to-teal-500",
    text: "text-emerald-300",
    glow: "shadow-emerald-500/40",
    x: 16,
    y: 34,
    order: 1,
    unlocked: true,
  },
  {
    id: "robot-valley",
    name: "Robot Valley",
    iconName: "star",
    blurb: "Meet machines that sense, think, and move.",
    topic: "Robotics & Agents",
    gradient: "from-slate-300 to-slate-500",
    text: "text-slate-200",
    glow: "shadow-slate-400/40",
    x: 33,
    y: 62,
    order: 2,
    unlocked: true,
  },
  {
    id: "data-forest",
    name: "Data Forest",
    iconName: "star",
    blurb: "Grow datasets and watch patterns bloom.",
    topic: "Data & Datasets",
    gradient: "from-teal-400 to-emerald-600",
    text: "text-teal-200",
    glow: "shadow-teal-500/40",
    x: 27,
    y: 16,
    order: 3,
    unlocked: true,
  },
  {
    id: "neural-peaks",
    name: "Neural Peaks",
    iconName: "star",
    blurb: "Climb the mountains of learning itself.",
    topic: "Neural Networks",
    gradient: "from-violet-400 to-indigo-600",
    text: "text-violet-200",
    glow: "shadow-violet-500/40",
    x: 48,
    y: 30,
    order: 4,
    unlocked: false,
  },
  {
    id: "vision-volcano",
    name: "Vision Volcano",
    iconName: "star",
    blurb: "Teach AI to see the world around it.",
    topic: "Computer Vision",
    gradient: "from-orange-400 to-red-600",
    text: "text-orange-200",
    glow: "shadow-orange-500/40",
    x: 58,
    y: 66,
    order: 5,
    unlocked: false,
  },
  {
    id: "language-lagoon",
    name: "Language Lagoon",
    iconName: "star",
    blurb: "Dive into how machines understand words.",
    topic: "Natural Language",
    gradient: "from-sky-400 to-cyan-600",
    text: "text-sky-200",
    glow: "shadow-sky-500/40",
    x: 66,
    y: 22,
    order: 6,
    unlocked: false,
  },
  {
    id: "prompt-planet",
    name: "Prompt Planet",
    iconName: "star",
    blurb: "Orbit the art of talking to AI.",
    topic: "Prompt Engineering",
    gradient: "from-fuchsia-400 to-purple-600",
    text: "text-fuchsia-200",
    glow: "shadow-fuchsia-500/40",
    x: 80,
    y: 46,
    order: 7,
    unlocked: false,
  },
  {
    id: "robotics-harbor",
    name: "Robotics Harbor",
    iconName: "star",
    blurb: "Dock, build, and ship real creations.",
    topic: "Building & Deployment",
    gradient: "from-amber-400 to-yellow-600",
    text: "text-amber-200",
    glow: "shadow-amber-500/40",
    x: 42,
    y: 82,
    order: 8,
    unlocked: false,
  },
  {
    id: "innovation-city",
    name: "Innovation City",
    iconName: "star",
    blurb: "Where young builders become inventors.",
    topic: "AI Entrepreneurship",
    gradient: "from-indigo-400 to-blue-600",
    text: "text-indigo-200",
    glow: "shadow-indigo-500/40",
    x: 72,
    y: 80,
    order: 9,
    unlocked: false,
  },
  {
    id: "space-observatory",
    name: "Space Observatory",
    iconName: "star",
    blurb: "Look outward. Build for tomorrow.",
    topic: "Frontier AI",
    gradient: "from-indigo-300 to-violet-700",
    text: "text-indigo-100",
    glow: "shadow-indigo-400/40",
    x: 88,
    y: 16,
    order: 10,
    unlocked: false,
  },
];
